### ISSUE TITLE
typo in 'buy me a coffee' button

### ISSUE THREAD

**Issue by tagby-haedongJeon** [Flajt/flutter_donation_buttons#3]
it shows "buy me a coffe"
one more "e" required

buyMeACoffeeButton.dart → line 22

**Comment by Flajt** [comment]
Thank you, I will fix it in the next couple of days.
For now you can overwrite the text to fix it for now.

Hope you like the package.

**Comment by Haedong-Jeon** [comment]
thank you for the reply. I like your package very much. thank you for the great work
