### ISSUE TITLE
Button Style

### ISSUE THREAD

**Issue by collodi** [Flajt/flutter_donation_buttons#5]
Is there a way to pass a style to the buttons?
I'm trying to manipulate the size of the button, and something like this would be nice.

```
PatreonButton(
    ...
    style: ElevatedButton.styleFrom(
      minimumSize: const Size.fromHeight(50),
    ),
),
```

Thanks for the awesome package!

**Comment by Flajt** [comment]
Thank your for using the package, happy you like it.
Currently it's not possible however I agree it would be helpfull (especially with long text).

I add that soon

**Comment by Flajt** [comment]
Do you think size is enough?
Or would you want some other values exposed as well?

**Comment by collodi** [comment]
Is it possible to expose the whole style attribute?

**Comment by Flajt** [comment]
In theory yes, however you would need to pass in the color manually as well I think. 
As this this is currently abstracted away in the button.

**Comment by collodi** [comment]
How about using the .merge function on the style?
Something like `(internal button style).merge(passed in button style)`?

**Comment by collodi** [comment]
Or the other way around if you want the users to be able to override the color.

**Comment by Flajt** [comment]
Sounds like a good idea, I will try that. I will add a toogle if people want to override the button and that should take care of it.

**Comment by Flajt** [comment]
@collodi Should be implemented now.
Version 0.1.6 has been pushed a second ago and should appear soon on pub.dev.
Hope it works as intended.
