### ISSUE TITLE
Open donate page should be allowed to launch from external applications

### ISSUE THREAD

**Issue by FriesI23** [Flajt/flutter_donation_buttons#6]
Accessing donate URL from browser can help avoid granting internet permission on android. This can be beneficial for minimize permissions if App doesn't require connect internet.

I can submit a PR to implement this feature.

**Comment by Flajt** [comment]
The new version should be on its way to pub.dev. I haven't tested anything, so if it breaks, pls open an issue.
And thanks a lot for the contribution, I appreciate it.
