### ISSUE TITLE
Github sponsors

### ISSUE THREAD

**Issue by bettysteger** [Flajt/flutter_donation_buttons#9]
I would like to see a [Github sponsors](https://github.com/sponsors/bettysteger) button ;)

**Comment by Flajt** [comment]
Good idea, I will be on it.

**Comment by Flajt** [comment]
Added the Button, it's in the newest version: 0.4.7

It has similar features to the other buttons, the minimal example can be found in the example section on pub.dev

**Comment by bettysteger** [comment]
Thank you so much! 

It works, i just need to add 

```
import 'package:flutter_donation_buttons/donationButtons/githubSponsorButton.dart';
import 'package:flutter_donation_buttons/flutter_donation_buttons.dart';
```

and for the others just 

```
import 'package:flutter_donation_buttons/flutter_donation_buttons.dart';
```

is necessary ;)

**Comment by Flajt** [comment]
Thanks for mentioning that, I will fix that in the next version. I forgott that I had a barrel file XD

**Comment by Flajt** [comment]
Should be fixed now
